### PR TITLE
Add Pull Request template

### PR DESCRIPTION
**Pull request by dserodio**
Good PRs always have a description and begin with the **why**, so I'm adding a PR template to remind contributors to add this information.

### CODE REVIEW

**Comment by dserodio** [comment]
It's not a good practice to ignore failed checks, but since this PR doesn't change any behavior and I don't have time to shave this yak (alpha versions of the Orb) at the moment, I will have to 😕

**Comment by carlosrfjunior** [comment]
@dserodio this project is old and I believe that CircleCI changed the format because of it. We need to revise the new format and apply the normalization.

**Comment by dserodio** [comment]
Thanks @carlosrfjunior! Can you review the PR please? 🙂

**Review by carlosrfjunior — APPROVED** [review]

**Comment by carlosrfjunior** [comment]
@dserodio done 👍

**Pull request merged**
